### ISSUE TITLE
Documentation - Utils pack

### ISSUE THREAD

**Issue by AFungo** [AFungo/abmodel-facturas-app#121]

**Comment by AFungo** [comment]
@yeografik i need you check the documentation of the methods copyFilters(), transferFilters() and separateWithholdingSpecialFilter() of the class FiltersUtils.java . It's be great if you check the rest of the comments.

**Comment by yeografik** [comment]
> @yeografik i need you check the documentation of the methods copyFilters(), transferFilters() and separateWithholdingSpecialFilter() of the class FiltersUtils.java . It's be great if you check the rest of the comments.

Done it
